// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXaCK6UcT8g3M0rHdARj3atQ8BiXoPzUk',
    appId: '1:249725766801:web:3b864bc8848549c1b78330',
    messagingSenderId: '249725766801',
    projectId: 'recipe-bot-ef534',
    authDomain: 'recipe-bot-ef534.firebaseapp.com',
    storageBucket: 'recipe-bot-ef534.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDqi1oYyB7oLO9Rqb2EMOXdm88T3sWqTI',
    appId: '1:249725766801:android:245b83107193b382b78330',
    messagingSenderId: '249725766801',
    projectId: 'recipe-bot-ef534',
    storageBucket: 'recipe-bot-ef534.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuqBQ1Y0vbL9ygIeIprYAvcXnMTzFfyoc',
    appId: '1:249725766801:ios:fe718ed58f3b0729b78330',
    messagingSenderId: '249725766801',
    projectId: 'recipe-bot-ef534',
    storageBucket: 'recipe-bot-ef534.firebasestorage.app',
    iosBundleId: 'com.luisfelipealves.recipeBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuqBQ1Y0vbL9ygIeIprYAvcXnMTzFfyoc',
    appId: '1:249725766801:ios:fe718ed58f3b0729b78330',
    messagingSenderId: '249725766801',
    projectId: 'recipe-bot-ef534',
    storageBucket: 'recipe-bot-ef534.firebasestorage.app',
    iosBundleId: 'com.luisfelipealves.recipeBot',
  );
}
